"""update awards table

Revision ID: 1bbd55901cc9
Revises: 953fc7a0b769
Create Date: 2026-03-06 22:35:52.137275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbd55901cc9'
down_revision: Union[str, Sequence[str], None] = '953fc7a0b769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
