"""add image_path to actors

Revision ID: 953fc7a0b769
Revises: 40f680717d9b
Create Date: 2026-03-06 13:53:24.498917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953fc7a0b769'
down_revision: Union[str, Sequence[str], None] = '40f680717d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'image_path')
    # ### end Alembic commands ###
