"""district table

Revision ID: e0b556173c5d
Revises: e59993ee19a0
Create Date: 2026-02-11 21:38:52.568975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b556173c5d'
down_revision: Union[str, Sequence[str], None] = 'e59993ee19a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_master',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=30), nullable=False),
    sa.Column('district_code', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('district_id')
    )
    op.create_index(op.f('ix_district_master_district_id'), 'district_master', ['district_id'], unique=False)
    op.drop_index(op.f('ix_state_master_id'), table_name='state_master')
    op.drop_table('state_master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('state_master_pkey'))
    )
    op.create_index(op.f('ix_state_master_id'), 'state_master', ['id'], unique=False)
    op.drop_index(op.f('ix_district_master_district_id'), table_name='district_master')
    op.drop_table('district_master')
    # ### end Alembic commands ###
